# What are Numpy and Numpy arrays?

Python objects

*  high-level number objects: integers, floating point
*  containers: lists (costless insertion and append), dictionaries (fast lookup)

Numpy provides

*  extension package to Python for multi-dimensional arrays
*  closer to hardware (efficiency)
*  designed for scientific computation (convenience)
*  Also known as array oriented computing


In [2]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

For example, An array containing:
*  values of an experiment/simulation at discrete time steps
*  signal recorded by a measurement device, e.g. sound wave
*  pixels of an image, grey-level or colour
*  3-D data measured at different X-Y-Z positions, e.g. MRI scan
*  ...

Why it is useful: Memory-efficient container that provides fast numerical operations.

In [3]:
L = range(1000)

In [4]:
%timeit [i**2 for i in L]

1000 loops, best of 3: 370 µs per loop


In [5]:
a = np.arange(1000)

In [6]:
%timeit a**2

The slowest run took 27.93 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.3 µs per loop


In [6]:
np.array?

In [7]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [7]:
import numpy as np

# Array Creation

In [8]:
a = np.array([0, 1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
len(a)

4

In [12]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [13]:
b, b.ndim, b.shape, len(b)

(array([[0, 1, 2],
        [3, 4, 5]]), 2, (2, 3), 2)

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [16]:
type(b)

numpy.ndarray

In [17]:
b.dtype

dtype('int64')

In [19]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [26]:
x = np.linspace( 0, 2*pi, 20 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [27]:
x

array([ 0.        ,  0.33069396,  0.66138793,  0.99208189,  1.32277585,
        1.65346982,  1.98416378,  2.31485774,  2.64555171,  2.97624567,
        3.30693964,  3.6376336 ,  3.96832756,  4.29902153,  4.62971549,
        4.96040945,  5.29110342,  5.62179738,  5.95249134,  6.28318531])

In [28]:
f

array([  0.00000000e+00,   3.24699469e-01,   6.14212713e-01,
         8.37166478e-01,   9.69400266e-01,   9.96584493e-01,
         9.15773327e-01,   7.35723911e-01,   4.75947393e-01,
         1.64594590e-01,  -1.64594590e-01,  -4.75947393e-01,
        -7.35723911e-01,  -9.15773327e-01,  -9.96584493e-01,
        -9.69400266e-01,  -8.37166478e-01,  -6.14212713e-01,
        -3.24699469e-01,  -2.44929360e-16])

In [29]:
print(x)

[ 0.          0.33069396  0.66138793  0.99208189  1.32277585  1.65346982
  1.98416378  2.31485774  2.64555171  2.97624567  3.30693964  3.6376336
  3.96832756  4.29902153  4.62971549  4.96040945  5.29110342  5.62179738
  5.95249134  6.28318531]


In [30]:
print(f)

[  0.00000000e+00   3.24699469e-01   6.14212713e-01   8.37166478e-01
   9.69400266e-01   9.96584493e-01   9.15773327e-01   7.35723911e-01
   4.75947393e-01   1.64594590e-01  -1.64594590e-01  -4.75947393e-01
  -7.35723911e-01  -9.15773327e-01  -9.96584493e-01  -9.69400266e-01
  -8.37166478e-01  -6.14212713e-01  -3.24699469e-01  -2.44929360e-16]


In [32]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [33]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [34]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [36]:
d = np.arange(10000)
print(d)

[   0    1    2 ..., 9997 9998 9999]


In [39]:
e = d.reshape(100,100)
print(e)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Basic Operations

Arithmetic operators on arrays apply elementwise. 
A new array is created and filled with the result.

In [42]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [43]:
c = a-b
c

array([20, 29, 38, 47])

In [44]:
b**2

array([0, 1, 4, 9])

In [45]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [47]:
a<35

array([ True,  True, False, False], dtype=bool)

the product operator * operates elementwise in NumPy arrays

In [48]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [49]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [50]:
np.dot(A, B)                # another matrix product

array([[5, 4],
       [3, 4]])

+= and *=, act in place to modify an existing array rather than create a new one.

In [55]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a,b, sep='\n')

[[1 1 1]
 [1 1 1]]
[[ 0.87250732  0.21412366  0.65552038]
 [ 0.87519485  0.83180129  0.90664714]]


In [56]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [57]:
b += a
b

array([[ 3.87250732,  3.21412366,  3.65552038],
       [ 3.87519485,  3.83180129,  3.90664714]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [58]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name
c = a+b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [59]:
c.dtype.name

'float64'

# References

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html